//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.MainDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactsEmail
    {
        public int ID { get; set; }
        public int ContactID { get; set; }
        public string E_mail_Address { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
