//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.MainDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportMail
    {
        public System.Guid ID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Type { get; set; }
        public bool Recursive { get; set; }
        public string Hostname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<bool> SSL { get; set; }
        public Nullable<bool> SkipSslValidation { get; set; }
        public Nullable<System.DateTime> ScanFromDate { get; set; }
        public Nullable<System.DateTime> ScanToDate { get; set; }
        public string Status { get; set; }
        public string MailboxName { get; set; }
        public string MailboxCurrent { get; set; }
        public Nullable<long> MessageCount { get; set; }
        public Nullable<bool> Processing { get; set; }
        public Nullable<bool> Error { get; set; }
        public Nullable<long> LastSeenId { get; set; }
        public string LastSeenMessageId { get; set; }
        public Nullable<System.DateTime> LastSeenMessageDate { get; set; }
        public Nullable<int> PageSize { get; set; }
        public Nullable<int> OffSet { get; set; }
    }
}
