//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.MainDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainDatabasePostProcessingQueue
    {
        public int TaskID { get; set; }
        public Nullable<int> TaskCommand { get; set; }
        public byte[] TaskArg1 { get; set; }
        public byte[] TaskArg2 { get; set; }
        public Nullable<int> TaskDataInt { get; set; }
        public Nullable<long> TaskDataBigInt { get; set; }
        public Nullable<System.Guid> TaskDataGuid { get; set; }
        public string TaskDataString { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public Nullable<short> Priority { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsScheduled { get; set; }
        public Nullable<System.DateTime> FetchedAt { get; set; }
        public Nullable<System.DateTime> Hangfire { get; set; }
        public Nullable<bool> AutoDelete { get; set; }
        public Nullable<bool> Abort { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
    }
}
