//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExchangeEntities : DbContext
    {
        public ExchangeEntities()
            : base("name=ExchangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MsgTrackingExtendedLog> MsgTrackingExtendedLogs { get; set; }
        public virtual DbSet<MsgTrackingLog> MsgTrackingLogs { get; set; }
        public virtual DbSet<MsgTrackingLogsAttachment> MsgTrackingLogsAttachments { get; set; }
        public virtual DbSet<MsgTrackingLogsBounce> MsgTrackingLogsBounces { get; set; }
        public virtual DbSet<MsgTrackingLogsCategory> MsgTrackingLogsCategories { get; set; }
        public virtual DbSet<MsgTrackingLogsHeader> MsgTrackingLogsHeaders { get; set; }
        public virtual DbSet<MsgTrackingLogsReceipt> MsgTrackingLogsReceipts { get; set; }
        public virtual DbSet<MsgTrackingLogsRecipientAddress> MsgTrackingLogsRecipientAddresses { get; set; }
        public virtual DbSet<MsgTrackingLogsExtended> MsgTrackingLogsExtendeds { get; set; }
        public virtual DbSet<MsgTrackingLogsExtendedJunk> MsgTrackingLogsExtendedJunks { get; set; }
        public virtual DbSet<MsgTrackingLogsExtendedMain> MsgTrackingLogsExtendedMains { get; set; }
        public virtual DbSet<MsgTrackingLogsExtendedPromotion> MsgTrackingLogsExtendedPromotions { get; set; }
    }
}
