//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTrackingExtendedLog
    {
        public string message_body { get; set; }
        public string message_body_type { get; set; }
        public string attachments { get; set; }
        public string sender_name { get; set; }
        public string display_to { get; set; }
        public string display_cc { get; set; }
        public string journal_message_id { get; set; }
        public long MsgTrackingLogsID { get; set; }
        public Nullable<System.Guid> conversation_id { get; set; }
        public Nullable<int> conversation_count { get; set; }
        public string message_body_sha1 { get; set; }
        public string message_body_text { get; set; }
        public Nullable<long> list_unsubscribe_headers_id { get; set; }
        public Nullable<bool> is_message_receipt { get; set; }
        public string from_address { get; set; }
        public string from_name { get; set; }
    
        public virtual MsgTrackingLog MsgTrackingLog { get; set; }
    }
}
