//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTrackingLogsHeader
    {
        public long ID { get; set; }
        public long MsgTrackingLogsID { get; set; }
        public short Line { get; set; }
        public string FieldName { get; set; }
        public string FieldBody { get; set; }
    
        public virtual MsgTrackingLog MsgTrackingLog { get; set; }
    }
}
