//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTrackingLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsgTrackingLog()
        {
            this.MsgTrackingLogsBounces = new HashSet<MsgTrackingLogsBounce>();
            this.MsgTrackingLogsCategories = new HashSet<MsgTrackingLogsCategory>();
            this.MsgTrackingLogsHeaders = new HashSet<MsgTrackingLogsHeader>();
            this.MsgTrackingLogsReceipts = new HashSet<MsgTrackingLogsReceipt>();
            this.MsgTrackingLogsRecipientAddresses = new HashSet<MsgTrackingLogsRecipientAddress>();
            this.MsgTrackingLogsAttachments = new HashSet<MsgTrackingLogsAttachment>();
        }
    
        public string client_ip { get; set; }
        public string client_hostname { get; set; }
        public string server_ip { get; set; }
        public string server_hostname { get; set; }
        public string source_context { get; set; }
        public string connector_id { get; set; }
        public string source { get; set; }
        public string event_id { get; set; }
        public Nullable<long> internal_message_id { get; set; }
        public string message_id { get; set; }
        public string recipient_address { get; set; }
        public string recipient_status { get; set; }
        public Nullable<long> total_bytes { get; set; }
        public Nullable<int> recipient_count { get; set; }
        public string related_recipient_address { get; set; }
        public string reference { get; set; }
        public string message_subject { get; set; }
        public string sender_address { get; set; }
        public string return_path { get; set; }
        public string message_info { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    
        public virtual MsgTrackingExtendedLog MsgTrackingExtendedLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsgTrackingLogsBounce> MsgTrackingLogsBounces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsgTrackingLogsCategory> MsgTrackingLogsCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsgTrackingLogsHeader> MsgTrackingLogsHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsgTrackingLogsReceipt> MsgTrackingLogsReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsgTrackingLogsRecipientAddress> MsgTrackingLogsRecipientAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsgTrackingLogsAttachment> MsgTrackingLogsAttachments { get; set; }
    }
}
