//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTrackingLogsBounce
    {
        public long ID { get; set; }
        public long MsgTrackingLogsID { get; set; }
        public long source_id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> smtp_code { get; set; }
        public string extended_smtp_code { get; set; }
        public string error_message { get; set; }
        public string recipient_address { get; set; }
        public string server_address { get; set; }
    
        public virtual MsgTrackingLog MsgTrackingLog { get; set; }
    }
}
