//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTrackingLogsExtended
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string client_ip { get; set; }
        public string client_hostname { get; set; }
        public string server_ip { get; set; }
        public string server_hostname { get; set; }
        public string source_context { get; set; }
        public string connector_id { get; set; }
        public string source { get; set; }
        public string event_id { get; set; }
        public Nullable<long> internal_message_id { get; set; }
        public string message_id { get; set; }
        public string recipient_address { get; set; }
        public string recipient_status { get; set; }
        public Nullable<long> total_bytes { get; set; }
        public Nullable<int> recipient_count { get; set; }
        public string related_recipient_address { get; set; }
        public string reference { get; set; }
        public string message_subject { get; set; }
        public string sender_address { get; set; }
        public string return_path { get; set; }
        public string message_info { get; set; }
        public string message_body { get; set; }
        public string message_body_text { get; set; }
        public string message_body_type { get; set; }
        public string attachments { get; set; }
        public string sender_name { get; set; }
        public string display_to { get; set; }
        public string display_cc { get; set; }
    }
}
