//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTrackingLogsReceipt
    {
        public long MsgTrackingLogsID { get; set; }
        public long receipt_id { get; set; }
        public byte receipt_type { get; set; }
    
        public virtual MsgTrackingLog MsgTrackingLog { get; set; }
    }
}
