//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTrackingLogsCategory
    {
        public long MsgTrackingLogsID { get; set; }
        public int Category { get; set; }
        public Nullable<int> Assignor { get; set; }
    
        public virtual MsgTrackingLog MsgTrackingLog { get; set; }
    }
}
