//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Databases.Exchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTrackingLogsRecipientAddress
    {
        public long ID { get; set; }
        public string recipient_address { get; set; }
        public long MsgTrackingLogsID { get; set; }
        public string recipient_name { get; set; }
        public string domain_part { get; set; }
        public Nullable<long> MsgTrackingLogsBounceID { get; set; }
        public string recipient_type { get; set; }
        public Nullable<long> MsgTrackingLogsReceiptDeliveryID { get; set; }
    
        public virtual MsgTrackingLog MsgTrackingLog { get; set; }
    }
}
